language: eng  # Set to 'eng' for English text extraction

save_data: True  # Ensures data and images are saved


# Subdirectory for all results
results_folder: "./output/all_results"  

# Subdirectories for specific outputs
summary_folder: "./output/summaries"  # Folder for summary outputs
flashcard_folder: "./output/flashcards"  # Folder for flashcard outputs
query_folder: "./output/search_queries"  # Folder for search query outputs

use_clipboard_for_input: False  # Set to False to process images from the directory

path_to_directory: "./input/images"  # Dynamic directory for input images, relative to the script's location

print_result: True  # This will print the result in the console
pdf_path: "./input/pdfs" 
